terraform {
  required_version = ">= 1.0"
  
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = var.project_id
  region  = var.region
}

# 1. Artifact Registry Repository
resource "google_artifact_registry_repository" "repo" {
  location      = var.region
  repository_id = "strejda-repo"
  description   = "Docker repository for Strejda OpenCode application"
  format        = "DOCKER"
}

# 2. OpenCode Server Service
resource "google_cloud_run_service" "opencode_server" {
  name     = "opencode-server"
  location = var.region

  template {
    spec {
      containers {
        image = var.server_image
        
        # Cloud Run automatically injects PORT environment variable (defaults to 8080)
        ports {
          name           = "http1"
          container_port = 8080
        }
        
        env {
          name  = "NODE_ENV"
          value = "production"
        }
        
        env {
          name  = "HOSTNAME"
          value = "0.0.0.0"
        }
        
        env {
          name  = "OPENCODE_MODEL"
          value = var.opencode_model
        }
        
        env {
          name  = "OPENAI_API_KEY"
          value = var.openai_api_key
        }
        
        # Resource limits and requests - optimized for free tier
        resources {
          limits = {
            cpu    = var.server_cpu
            memory = var.server_memory
          }
          requests = {
            cpu    = "100m"
            memory = "128Mi"
          }
        }
      }
      
      # Timeout for requests (max 3600s for Cloud Run)
      timeout_seconds = 300
      
      # Service account (uses default compute service account if not specified)
      # service_account_name = "your-service-account@opencode-shopper.iam.gserviceaccount.com"
    }
    
    metadata {
      annotations = {
        # Autoscaling configuration - optimized for cost
        "autoscaling.knative.dev/minScale" = "0"  # Scale to zero when idle
        "autoscaling.knative.dev/maxScale" = "2"  # Limit concurrent instances to 2
        
        # CPU allocation - only allocate during request processing
        "run.googleapis.com/cpu-throttling" = "true"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }

  # Prevent destroying the service accidentally
  lifecycle {
    prevent_destroy = false
  }
}

# Allow public access to Server
resource "google_cloud_run_service_iam_member" "server_public" {
  count    = var.allow_public_access ? 1 : 0
  service  = google_cloud_run_service.opencode_server.name
  location = google_cloud_run_service.opencode_server.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}

# 3. Next.js API Service
resource "google_cloud_run_service" "next_api" {
  name     = "opencode-next-api"
  location = var.region

  template {
    spec {
      containers {
        image = var.next_api_image
        
        ports {
          name           = "http1"
          container_port = 8080
        }

        # Connect API to the OpenCode Server Cloud Run URL
        # This URL is automatically generated by Cloud Run and will be in the format:
        # https://opencode-server-<hash>.<region>.run.app
        env {
          name  = "OPENCODE_URL"
          value = google_cloud_run_service.opencode_server.status[0].url
        }
        
        env {
          name  = "NODE_ENV"
          value = "production"
        }
        
        env {
          name  = "HOSTNAME"
          value = "0.0.0.0"
        }
        
        # Resource limits and requests - optimized for free tier
        resources {
          limits = {
            cpu    = var.next_api_cpu
            memory = var.next_api_memory
          }
          requests = {
            cpu    = "100m"
            memory = "128Mi"
          }
        }
      }
      
      timeout_seconds = 300
    }
    
    metadata {
      annotations = {
        "autoscaling.knative.dev/minScale"  = "0"  # Scale to zero when idle
        "autoscaling.knative.dev/maxScale"  = "2"  # Limit concurrent instances to 2
        "run.googleapis.com/cpu-throttling" = "true"
      }
    }
  }

  traffic {
    percent         = 100
    latest_revision = true
  }
  
  # Explicit dependency to ensure Server URL is available
  depends_on = [google_cloud_run_service.opencode_server]
  
  lifecycle {
    prevent_destroy = false
  }
}

# Allow public access to Next.js API
resource "google_cloud_run_service_iam_member" "api_public" {
  count    = var.allow_public_access ? 1 : 0
  service  = google_cloud_run_service.next_api.name
  location = google_cloud_run_service.next_api.location
  role     = "roles/run.invoker"
  member   = "allUsers"
}
